osx_image: xcode7
language: objective-c

before_install:
    - brew install caskroom/cask/brew-cask
    - brew cask install oclint

xcode_project: tunnelblick/Tunnelblick.xcodeproj

script:
    - third_party/ShellScriptToInstallAutotools.sh
    - cp -r tunnelblick/xcodeproj-versions/xcode\ 7.0/Tunnelblick.xcodeproj/* tunnelblick/Tunnelblick.xcodeproj
    - xcodebuild -project tunnelblick/Tunnelblick.xcodeproj -target Tunnelblick -configuration "Unsigned Release"
