os: osx
osx_image: xcode7.3
xcode_project: tunnelblick/Tunnelblick.xcodeproj
xcode_scheme: Tunnelblick
addons:
  homebrew:
    brewfile: true
env:
  matrix:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release
script: set -o pipefail && xcodebuild -project tunnelblick/Tunnelblick.xcodeproj -target Tunnelblick -configuration ${CONFIGURATION} -UseModernBuildSystem=NO build
