language: objective-c

branches:
  only:
    - master

xcode_project: tunnelblick/Tunnelblick.xcodeproj
osx_image: beta-xcode6.3

script:
    - third_party/ShellScriptToInstallAutotools.sh
    - xcodebuild test -project Swifternalization.xcodeproj -scheme SwifternalizationTests
