language: objective-c

branches:
  only:
    - master

xcode_project: tunnelblick/Tunnelblick.xcodeproj
osx_image: beta-xcode6.3

script:
    - third_party/ShellScriptToInstallAutotools.sh
    - cp -r tunnelblick/xcodeproj-versions/xcode\ 6.3/Tunnelblick.xcodeproj/* tunnelblick/Tunnelblick.xcodeproj
    - xcodebuild -project tunnelblick/Tunnelblick.xcodeproj
