language: objective-c

branches:
  only:
    - master

xcode_project: tunnelblick/Tunnelblick.xcodeproj
osx_image: xcode5

script:
    - third_party/ShellScriptToInstallAutotools.sh
    - cp -r tunnelblick/xcodeproj-versions/xcode5.1.1/Tunnelblick.xcodeproj/* tunnelblick/Tunnelblick.xcodeproj
#    - xcodebuild -workspace tunnelblick/Tunnelblick.xcodeproj/project.xcworkspace -scheme Tunnelblick -configuration "Unsigned Release"
#    - xctool -project tunnelblick/Tunnelblick.xcodeproj build -scheme Tunnelblick -configuration "Unsigned Release"
    - xcodebuild -project tunnelblick/Tunnelblick.xcodeproj -target Tunnelblick -configuration "Unsigned Release"
